### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by noraj** [zdhxiong/mdui#245]
Is that possible to have a translation in english please?

**Comment by lijialong1313** [comment]
I can give you some other material design UI layouts, such as Vuetify.

This UI layouts looks like a baby.

**Comment by Subilan** [comment]
Unfortunately the author doesn't have enough time or even shows no interest in it, as you can learn from his replies in other issues. The translation can be made by the community, however it also depends on the author's preference and the community's interest. In fact, from my perspective, the open-source mind here is not as enthusiastic as I once expected.

My suggestion is that you could use Vuetify instead which has better compatibility with Vue and similar appearance & animation to mdui (as their design is based on Material Design). However, if you just want things for vanilla JS, I think you may have to wait because mdui is, I think, the best practice in the area.

**Comment by DFFZMXJ** [comment]
> We’re open to accept PRs that translate our README into English. You’re welcome to submit one. ——[罗诗亚的回答][^zhihu]

[^zhihu]: https://www.zhihu.com/question/341348869/answer/796524261 "看来GitHub不支持插入参考文献"

**Comment by shirooo39** [comment]
+1 for english translation.

>if you just want things for vanilla JS, I think you may have to wait because mdui is, I think, the best practice in the area.

I highly agree with this.
I've tried a number of Material  Design frameworks but I find MDUI it probably the best among them (that is vanilla JS).
I want to give Vuetify a try, but I know nothing about Vue.
MDL just doesn't have much components and no longer updated for years.
Materialize is really good, but doens't suite my taste.
currently using an updated fork of Daemonite's Material Design fo Bootstrap 4 and it's pretty good.

if someday MDUI get translated into english, I'll definitely switch.

**Comment by shirooo39** [comment]
so, I came back after exactly a year after I posted my last comment.

this project seem to still don't have any english translation, BUT! I was able to get away simply by using a translator add-on that I installed on my Firefox, or Chrome's amazing built-in Google Translate on, well, any Chromium-based browsers.

the translated language is easily understandable, like 80% of it. you won't get lost.

I really wanna try out Vuetify because it seems to be more solidly built than MDUI, but MDUI is by far the best Vanilla JS Material Design framework available.

so my top Material Design framework for web app would be:
- Vuetify
- MDUI
- MCW
- MDL

Vuetify: reaaaaally good but need to learn Vue and JavaScript first.
MDUI: also really good, but no english support.
MCW: made by Google themself, a successor to MDL, but more difficult to use.
MDL: was really good, but outdated and no longer getting any more update for the rest of its life.

**Comment by Subilan** [comment]
So what does the "project translation" exactly mean? I thought it was a English translation of the document. Is it right?

**Comment by chisato2309** [comment]
> So what does the "project translation" exactly mean? I thought it was a English translation of the document. Is it right?

yeah, english translation of the docs
I could get away using a translator, but that's no fun as it messes up with some styling of the docs' site

**Comment by zdhxiong** [comment]
mdui2 has provided English documentation.
